### ISSUE TITLE
crop UI blocks Bdv Window

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#10]
make the crop UI non-blocking such that the user can inspect whether the crop is ok

**Comment by ASHISRAVINDRAN** [comment]
Hi Tischi,
I got a doubt!
The current version of the code for Crop UI is non-blocking. Technically speaking the Dialog box (which shows all the sliders for different axes) is MODELESS.
Thus even though the Crop UI is present always on the screen, a user has the freedom to dig through the z stacks or slide through the time in the BDV window. Is this the expected functionality or should the crop UI totally disappear from the screen when BDV window is in focus?
Anyway, I am pushing changes for the latter case where Crop UI moves to the background of BDV window.
Let me know if this is what is required, then we can close the issue & do some code cleanup. Else we can revert the changes! :)
