### ISSUE TITLE
UI problem in Crop on Ubuntu 16.04 LTS 

### ISSUE THREAD

**Issue by AlexisMaizel** [bigdataprocessor/bigdataprocessor2#105]
Hi Tischi, 

in the Crop module, all UI widgets (except for the `t` sliders) do not work on Ubuntu 16.04. 
Bunch of `awt`related errors in the console.

**Comment by tischi** [comment]
And we just submitted the manuscript... ;-)

1. Did you download a new Fiji? There were many many changes within Fiji recently, so maybe updating an old one may not suffice.
2. Is that specific to this Ubuntu OS? For example, do you also have access to another computer, e.g. with Windows, Mac or another Linux OS? Do you know whether it works there for you?

**Comment by nornil** [comment]
I just tried with MacOSX  for both one and two channel data (tif stacks) and all sliders appeared to behave normally.. I hope downloading a new Fiji will do the trick..

**Comment by AlexisMaizel** [comment]
No problems on MacOS.
A fresh install of Fiji + update *solved all the problems* I mentioned in the different tickets (Widgets not responding, hang if cropping w/ default voxel size) :-) 
Fingers crossed for the manuscript.

**Comment by tischi** [comment]
@AlexisMaizel just to be sure: **also works now on Ubuntu**?
