### ISSUE TITLE
Attempting to crop w/o specifying the voxel size beforehand hangs Fiji (Ubuntu 16.04)

### ISSUE THREAD

**Issue by AlexisMaizel** [bigdataprocessor/bigdataprocessor2#106]
every thing in the title :-)

**Comment by tischi** [comment]
1. Where does it hang exactly? Does below window still show? 

![image](https://user-images.githubusercontent.com/2157566/90021224-3ed9ba80-dcb1-11ea-9dcf-d7a3dafa07a3.png)

2. What does it show for the voxel size in the main window? 

![image](https://user-images.githubusercontent.com/2157566/90021282-55801180-dcb1-11ea-8efc-accbb02eac9e.png)

**Comment by tischi** [comment]
@AlexisMaizel 
Could you comment on above questions? Thanks a lot!
