### ISSUE TITLE
remove possibility to set voxel size to 0   

### ISSUE THREAD

**Issue by nornil** [bigdataprocessor/bigdataprocessor2#108]
processing afterwards e.g crop gives unsurprisingly java.lang.IllegalArgumentException: invalid range properties

**Comment by tischi** [comment]
ok like this?

![image](https://user-images.githubusercontent.com/2157566/90025639-a34b4880-dcb6-11ea-852e-d7c389eead9e.png)

**Comment by nornil** [comment]
yes  look ok!  Thanks!

Den ons 12 aug. 2020 kl 16:13 skrev Christian Tischer <
notifications@github.com>:
