### ISSUE TITLE
Does not recon Stack1 in Luxendo raw files

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#109]
It does not open Luxendo MuVi raw files that are in the folder called "Stack_1" ; just manually changing the name of the folder it works ; for the same reason , in the BDviewer, only stack0  is visible; for the rest, it is making my life much easier...!

**Comment by tischi** [comment]
Thank you for reporting this!

> that are in the folder called "Stack_1" ; just manually changing the name of the folder it works 

1. Could you tell me to what you rename it to?
2. Could you paste a screenshot of the folder structure?
3. Is that how the files come out of the Luxendo microscope?

**Comment by cikus3** [comment]
1. I used to rename the "stack_1 " to "stack_0"
2. attached below
3.Yes,it  is how files come out of the microscope
![data_struct_Lux](https://user-images.githubusercontent.com/35956783/94699988-ddd67680-0332-11eb-8a00-6fd525276949.JPG)

**Comment by tischi** [comment]
@cikus3 
Maybe you did not see this, but, currently, you have to **_manually_** choose with stack you want to open:
![image](https://user-images.githubusercontent.com/2157566/94785292-b4b7f380-03cf-11eb-9fcb-4c43def03396.png)
Here, stack `0` is chosen, but you can type any other number there, given it exists in the selected folder.

**Comment by cikus3** [comment]
Super! I ve tried to specify the Stack index, and now it works. Thanks!
