### ISSUE TITLE
Open EM Tiff planes not working

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#110]
Hello; I would like to use BDP2 for opening volumes acquired with the Lavision UMII ligth-sheet; the file saving scheme is the one attached (basically, it saves single planes and not volumes); ideally the EM Tiff opening options would help, I think; but it does not work (no window opens when I click on it..); I tried to use the Custom option with the following line " .*UltraII_C(?<C>.*).*.*Table Z(?<T>\d+) " and the file extension " .ome.tiff ". It works, but I can t find a way to specify the Z value, and it get open as a time lapse (= can t change the orientation of the volume..). Is this the right command to use? Better ideas?..Thanks!
![Lav scheme](https://user-images.githubusercontent.com/35956783/91968436-909fbe80-ed0c-11ea-9e60-3768316ec81c.JPG)

**Comment by tischi** [comment]
@cikus3 
I will upload a new version later today.
Could you please try tomorrow again and let me know if `Open > EM Tiff Slices` works now?
