### ISSUE TITLE
Is it possible to load multichannel volumes which have one file per plane and channel?

### ISSUE THREAD

**Issue by walkernoreen** [bigdataprocessor/bigdataprocessor2#116]
This is an amazing tool! Very much looking forward to the binning and cropping in particular!

The data format that BigStitcher produces is often one file per channel and per plane - is it possible to load this via the custom import (in the spirit of the EM import but for 2 channels)? I could only manage to import Z as T.

**Comment by tischi** [comment]
@walkernoreen 
Thanks for interest!
Currently, I do not support this.
Could you provide me with some minimal sample data set?

**Comment by walkernoreen** [comment]
Small mistake from my side: It was actually not bigstitcher that produced the per-plane data but the "save as sequence" afterwards. 
Anyways, here would be a sample dataset: https://cloud.mpi-cbg.de/index.php/s/IDOjvZS4WWFaTn8 . It's simply T0 of your mouse sample data resaved (so now has the Z & C counters that I meant). My actual use-case is huge data, so not really suitable for upload...

**Comment by tischi** [comment]
@walkernoreen 
Thanks a lot for the data. This looks quite similar to how Leica save their light sheet data if one choses Tiff as an output (see below). I am supporting this already, thus I am hopeful that I can implement your naming pattern without too much effort. I just have to think in terms of the user interface how I do it such that it does not become too complex. Probably adding another regular expression option is the most versatile.... I will have a look tomorrow.
![image](https://user-images.githubusercontent.com/2157566/94613799-73c3c000-02a5-11eb-9e31-bedbc417bce6.png)

**Comment by tischi** [comment]
@walkernoreen 
For testing it would be nice to have two timepoints. Could you share a second timepoint with me?

**Comment by walkernoreen** [comment]
Wow you are very fast! I was also thinking that a regex syntax exactly like for T and C, but then with Z could work.
Here is the multi timepoint data: https://cloud.mpi-cbg.de/index.php/s/m6jdG9f0D15wp7J

**Comment by tischi** [comment]
You were lucky as I was anyway working on this project very intensely during the last days, so I thought I push this through as well, because it is a very natural request and missing feature. In fact, I think I got it working already.

Please update!

This works for me: `.*_t(?<T>\d+).*_z(?<Z>\d+).*_c(?<C>\d+).*`
I also added it to the Help.

Let me know of any issues.

**Comment by tischi** [comment]
...and please be aware that saving the processed data to compressed Tiff files currently is super slow and it is not my fault 🙂  

https://forum.image.sc/t/bioformats-saving-with-compression-is-too-slow/20522/6

**Comment by walkernoreen** [comment]
Hi,

I just tried with the new version and it works like a charm for the mouse data (the one I shared). I now tried on my own data which is numbered a bit differently and get a strange error:

My naming structure: c[1,2] is the channel, the last number is the slice, there is no time.
<img width="259" alt="image" src="https://user-images.githubusercontent.com/44499183/94681505-de1b4580-0323-11eb-92cc-0b147ea08e1c.png">

Regex I tried (if you copy from raw please remove the ``):
`.*_c(?<C>\d+).*_(?<Z>\d+).*`

Error I get:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/44499183/94681736-35b9b100-0324-11eb-9121-f2dd25d64ae0.png">


If I pretend the z to be time and import it with the following regex, it does work (but now I have time...)
`.*_c(?<C>\d+).*_(?<T>\d+).*`

**Comment by tischi** [comment]
> and get a strange error

That is not a strange error, that is a data set without time :)

You could pretend that the 10 behind downsample is the time:

Maybe try something like this:
`.*sample(?<T>\d+).*_c(?<C>\d+).*_(?<Z>\d+).*`

I could change my code to also include the case without time...I guess I should?

**Comment by walkernoreen** [comment]
Ha I wasn't aware that time was required ...
With the "fake time" like you suggested the import now works!

Personally, I'd vote in favor of time not being a requirement :-), ... at least my use case right now is a big (TB) volume of a fixed sample, 2 channels. 
Is this not even similar to EM data , where you I guess also don't have time?

**Comment by tischi** [comment]
Yes, makes sense I'll support it...

Otherwise any questions? 
Please post in a new issue or here: https://forum.image.sc/t/bigdataprocessor/34963/11

**Comment by imagejan** [comment]
Hi all, great to see this discussion here!

@tischi you could consider using the [`FilePattern`](https://javadoc.scijava.org/SCIFIO/index.html?io/scif/FilePattern.html) class provided by SCIFIO (and, if that doesn't suit your needs, improve it by contributing upstream). I think these use cases of importing multi-file data are very common, and it's unfortunate that each project (e.g. BDP2, BigStitcher, etc.) is implementing their own, slightly differing, strategy...

**Comment by tischi** [comment]
@imagejan That looks great, however I am very close getting my own reinvention of the wheel working....
I will have to consider this for the future: https://github.com/bigdataprocessor/bigdataprocessor2/issues/118

**Comment by tischi** [comment]
@walkernoreen 
I uploaded a new version. 
Could you please check whether this works for you also in case you do not have a tag for time?

**Comment by walkernoreen** [comment]
Hi @tischi ,
I just checked both with and without time and now it's working perfectly!
