### ISSUE TITLE
Not opening Luxedo MuVi raw data after last FIJI/BDP2 update....

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#117]
Unfortunately, after having done the updated of the BDP2 plugin, the raw files from MuVI Luxendo can`t be opened...See below error descriptions; yesterday it was working!
I ve tried to install a new copy of FIJI + fresh BDP2, but same issue
![Error_BDP2_200930_1](https://user-images.githubusercontent.com/35956783/94701894-10816e80-0335-11eb-9a92-2d6e3a76c800.JPG)
![Error_BDP2_200930_2](https://user-images.githubusercontent.com/35956783/94701897-111a0500-0335-11eb-92d1-f0459c1fb6cd.JPG)

**Comment by tischi** [comment]
@cikus3 
It worked for me, maybe I accidentally uploaded a broken version at some point.
I am working on it quite a lot on it these days...
Could you please update again (I changed some things) and try again?
If it still does not work could you please paste a screenshot showing the folder and some file names?

**Comment by cikus3** [comment]
Thanks; I ve tried again (updating the plugin), but the problem persists and there are new strange stuff (channel window missing the names, macro window automatically opened,..): see below a summary. Note: another version of FIJI (where I did not update the plugins since about 1 week, is working fine); 
[201001_test_BDP2.pdf](https://github.com/bigdataprocessor/bigdataprocessor2/files/5310665/201001_test_BDP2.pdf)

**Comment by tischi** [comment]
ok thanks!
So you are saying with the version a week ago it works?
Then I will check whether I changed anything...

**Comment by cikus3** [comment]
Yes, an old version is still working (I can open the file and see them with DBV); with the current one,  I can t open the files; I m not sure about the time when I update the working version..but probably 1-2 weeks ago

**Comment by tischi** [comment]
OK, I think I found the bug: I accidentally remove a line of code that changes the file separator from `/` to `\` in case someone is using Windows. Since I am using a Mac I did not see this error.
Could you please update and try again?

**Comment by cikus3** [comment]
Bingo! yes, now the newly updated version works! Thanks!
