### ISSUE TITLE
Saving fails if pixel units are not specified

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#137]
Fix this by either making sure they are specified or showing a warning during the saving.

**Comment by tischi** [comment]
@manerotoni
Could you please provide me with one of the Viventis files where the unit cannot be read?

**Comment by manerotoni** [comment]
Please see 2 positions 2 time points in 
https://owncloud.gwdg.de/index.php/s/BXn7D2GD45gxTJQ
