### ISSUE TITLE
Viventis reg exp

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#138]
@manerotoni

Is the reg exp for Viventis always the same? I could add it as a "predefined file series".

**Comment by manerotoni** [comment]
Hello Tischi,

the current regular expression is  `t(?<T>\d+)_(?<C>.+)` the channel is alphanumeric, e.g. (H2BmCherry). User can change it so it will  not be always the same. However, typically users stick to it. Each position is saved in a different directory.
Here you can find 2 positions 2 time point examples in 
https://owncloud.gwdg.de/index.php/s/BXn7D2GD45gxTJQ

**Comment by tischi** [comment]
Thank you for the examples!

They have spaces in their folder names, seriously? 

😉 😦

**Comment by manerotoni** [comment]
Yes. Not sure if this is a default from the software or a choice by the users that one could eventually change.

**Comment by tischi** [comment]
> Not sure if this is a default from the software

Could you find out whether the naming scheme of the folders is always the same?
This would be **very important** for adding a "Open Viventis" menu item.

**Comment by tischi** [comment]
@manerotoni 
When opening the files you shared I have trouble reading the voxel size.
With just drag and drop onto Fiji I get something in `inches`.
When opening with the BioFormats Importer I get this error:
```
loci.formats.FormatException: Unmatched UUID: urn:uuid:30698dd6-7e62-47d6-aa94-d3154016fc6d
```
Can you reproduce this?

**Comment by manerotoni** [comment]
Hi @tischi,

may be the problem is due to the fact that I did not clean up the ome file after removing the time points. I edited the ome file in the shared data folder. Can you donwload it again?

Now with the original file and the reduced time point file I get no exception. 

Antonio

**Comment by tischi** [comment]
@manerotoni 

Works now!
