### ISSUE TITLE
Saving multiple Luxendo stacks

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#139]
Hi there; always happy  with BDP2, but I m wondering for some improvement: with the Luxendo MuVi microscope, if we acquire tiles or multiviews, we get different stacks; with BDP2 I can open them one by one, inspection, rename process and save them. However, if the stack are many, saving each stack can be very long (I have to save one, wait, save the other one, wait,..) Is there a way to save all the stacks in parallel?   A kind of batch saving where first I process all the stacks and then I launch the saving just once? I can probably open multiple version of BDP2 in parallel, start the savings, but I m worry is gonna crash my PC....Thanks

**Comment by cikus3** [comment]
Dear all, we just received from Luxendo upadate about the L-sheet acquisition software and unfortunately with the new file format/structure, the option "open Luxendo file series" on BPDP2 does not work anymore...Soren from Luxendo told me they ll get in touch with you to possibly update BDP2. Having said that, my request of this post "saving multiple stacks" is suspended, because at the moment we can`t even open the file..

**Comment by tischi** [comment]
>  if we acquire tiles or multiviews, we get different stacks; with BDP2 I can open them one by one, inspection, rename process and save them. However, if the stack are many, saving each stack can be very long (I have to save one, wait, save the other one, wait,..) Is there a way to save all the stacks in parallel? A kind of batch saving where first I process all the stacks and then I launch the saving just once?

That's why I added macro recording to BDP2! Can you try to see whether that works for you! I am happy to help if there are bugs.

**Comment by tischi** [comment]
...the trick is to, in the Save menu, click `[ Record only ]`! Then you can save the macro, and execute it at your convenience and chain (i.e. copy and paste) multiple recorded macros behind each other. If there is something systematic in your data you can of course also try to create a for-loop. 

As said, I am happy to assist.

**Comment by cikus3** [comment]
Ok, great thanks, I ll try to use it (once the issue of the new Luxendo file format will be solved);  I think the time has come for me to learn a bit more about coding and scripting..

________________________________

**Comment by tischi** [comment]
>  I think the time has come for me to learn a bit more about coding and scripting..

Definitely if you want to do batch processing of any kind. Scripting is, imho, the best option:
1. It is easy to share, because it is just text
2. It is easy to reproduce 
3. It is easy to debug (you just send me the script and I look at it)
4. It is easy to publish

**Comment by cikus3** [comment]
It works! I managed to write a macro where I can save/rename 4 different Luxendo stacks, just in one click; I had in the past some issue with the memory required of he task...but I can`t reproduce the error; so, thanks, I`m gonna close now the Issue;
