### ISSUE TITLE
save data as HDF5/XML?

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#153]
hello; I`ve heard in the recent Neubias webinar about BDP2 (very useful, btw; thanks!) that is possible to save teh data as HDF5; however I can only find the option to save as TIFF Volumes, TIFF PLanes,  IMARIS.  The IMARIS option is saving as HDF5, but the XML file is missing (that can be useful to open the file with BigSticther. Am I missing something? Is there a way to save as HDF5/XML? Thanks

**Comment by tischi** [comment]
>  but the XML file is missing (that can be useful to open the file with BigSticther. Am I missing something? Is there a way to save as HDF5/XML? Thanks

You are not missing anything! That's missing, because one can open .ims files directly in BigDataViewer in Fiji using [ Plugins > BigDataViewer > Open Imaris (experimental) ]. However, that may not work for BigStitcher indeed. 

@NicoKiaru @tpietzsch Can you  comment/help here? I think we should add a bdv.xml with an `ImarisImageLoader` to the output of BDP2. You have been looking into this, didn't you? Does that work already? Could you give me some pointers how I could implement this?

**Comment by cikus3** [comment]
Ok, thanks; I ve actually tried to open that .ims file with BigStitcher and it does not work.

**Comment by NicoKiaru** [comment]
@cikus3 @tischi there will be a way to associate an xml file in order to open ims file in bigstitcher, but currently it lives in a dev branch of `bigdataviewer-core` : https://github.com/bigdataviewer/bigdataviewer-core/tree/imaris-xml

**Comment by tischi** [comment]
@cikus3 
I added an option to save as a normal BigDataViewer XML/HDF5.
Please let me know whether this is still of interest!
Then I will upload it to Fiji and you could try it out.

**Comment by cikus3** [comment]
Yes, thanks, on my side it would be very useful!

**Comment by tischi** [comment]
it should be there now....

**Comment by manerotoni** [comment]
Hello @tischi,
my question of #155 was if one could not use the imaris saving and just create an xml in addition. 
It just that saving takes long and one would not like to save many times and duplicate the data. 
Imaris understands BDV hdf5 but wants to convert it again to imaris format.  

I realized that after the last update Imaris saving does not seem to work anymore :-( It has frozen fiji after starting the writing of 21kb ims file.

**Comment by tischi** [comment]
> my question of #155 was if one could not use the imaris saving and just create an xml in addition.

The answer is: yes (see @NicoKiaru's post higher up in this thread).

**Comment by cikus3** [comment]
The HDF5 saving option is great and working for me; on my side, you can close the issue; thanks
