### ISSUE TITLE
create xml for bigdataviewer and ilastik

### ISSUE THREAD

**Issue by manerotoni** [bigdataprocessor/bigdataprocessor2#155]
Dear @tischi,

the BDP2 works quite well also with Viventis data. Thanks!

I was wondering if one can use  the imaris data saving and save also an xml for bigdataviewer. Ideally also some kind of xml data for ilastik. One conversion and you gets a data set that is compatible with 3 different software!
Basically it would be only one option 
 "save as h5 (imaris, BDV, ilastik)"

Would it be possible? I can also try to modify the BDP2 code to allow for this option.

**Comment by tischi** [comment]
Yes, totally, may I ask you join join the discussion in this thread:
https://github.com/bigdataprocessor/bigdataprocessor2/issues/153
