### ISSUE TITLE
New Luxendo File Format

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#160]
@cikus3 
Could you please remind Luxendo to contact me regarding their new file format?

**Comment by cikus3** [comment]
Yes, I ll do it with pleasure

---
Alessandro Ciccarelli
Light Sheet Specialist
CALM - Crick Advanced Light Microscopy Facility
The Francis Crick Institute
1 Midland Road - London -NW1 1AT
United Kingdom

T: +442037960913
E: alessandro.ciccarelli@crick.ac.uk<mailto:alessandro.ciccarelli@crick.ac.uk>
W: www.crick.ac.uk<http://www.crick.ac.uk/>

**Comment by tischi** [comment]
It should work now.
