### ISSUE TITLE
"directory not found"

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#164]
Hi all, when I try to open  Luxendo files with BDP2 I get a strange message mentioning Viventis(see attachment); if I close it, the program works fine, but that error is a bit strange; Btw, it is a minor issue and does not affect my work;
![BDP2_error_210325](https://user-images.githubusercontent.com/35956783/112489093-071e0f80-8d76-11eb-9ad6-d51a83c0b849.JPG)

**Comment by tischi** [comment]
Thanks!
I will upload a fix later today.
