### ISSUE TITLE
Error when opening floating point ICS/IDS

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#169]
When opening a floating point ICS/IDS file as output by Huygens deconvolution with the Bio-Formats bridge I got an error in BDP2...

@NicoKiaru, do you maybe have experience with this? I will debug it myself, the issue may be on the BDP2 end.

**Comment by NicoKiaru** [comment]
Interesting! I think I never tested a float typed image before using bf-bridge. Let me know how it goes. You can try bdv-pg directly and see if it works already. I wouldn't bet a lot of money on it ;-).

**Comment by tischi** [comment]
In fact, after some modifications in BDP2, it just works 🥳 

<img width="651" alt="image" src="https://user-images.githubusercontent.com/2157566/118971442-b985e380-b96f-11eb-8088-15c6f9c66803.png">
