### ISSUE TITLE
Opening a single volume tif image stack

### ISSUE THREAD

**Issue by anorak94** [bigdataprocessor/bigdataprocessor2#172]
I have a single .tif file which is around 10 gb. I want to open it through bpd2. I have tried using "Open custom file series" and "Open predefined file series > Open single tiff volume" but all of them return that the regular expression did not find the file specified. I have tried moving the .tif file to a separate folder and renaming it as image-0001.tif but that doesnt seem to work either. What is the right way to do this kind of operation in bpd2.

**Comment by tischi** [comment]
Dear @anorak94,

`[ Open predefined file series > Open single tiff volume ]` should work!

I just tried it by saving the ImageJ sample image `mri-stack.tif` (`[ File > Open Samples > MRI Stack ]` on the Desktop and was able to open it.

Could you please also try saving a simple TIFF stack and open it?

Maybe there is something special to your image...?

Do you have a smaller image for me to share with me such that I could test it?

**Comment by anorak94** [comment]
I tried the same thing which you said and it gives me this error log 
<img width="1168" alt="Screenshot 2021-06-28 at 19 09 16" src="https://user-images.githubusercontent.com/45297533/123676645-81ae6d80-d844-11eb-9b5a-065803459b90.png">

**Comment by anorak94** [comment]
<img width="539" alt="Screenshot 2021-06-28 at 19 11 36" src="https://user-images.githubusercontent.com/45297533/123676845-b91d1a00-d844-11eb-8559-7ae6ba99cd34.png">
<img width="815" alt="Screenshot 2021-06-28 at 19 11 10" src="https://user-images.githubusercontent.com/45297533/123676851-ba4e4700-d844-11eb-9833-baa516782a66.png">

**Comment by anorak94** [comment]
These are the steps i follow and that gives me the first error log

**Comment by anorak94** [comment]
I tried opening these files on an ubuntu machine as well the error is the same, no matching files found

**Comment by tischi** [comment]
This is very strange.... I will have a look at it asap!
It may take some time, because I am running an EMBO course this week.

**Comment by tischi** [comment]
Something you could try in-between is: `[ BDP2 > Open > Open Bio-Formats... ]`

**Comment by tischi** [comment]
I had another look but I could not find out what is going on...

Could you please also post here the output in the ImageJ log window?

@NicoKiaru Could you do me a favor and try out `[ Open predefined file series > Open single tiff volume ]`? Does it work for you?

**Comment by anorak94** [comment]
This works but it loads the z stack as the time channel

**Comment by tischi** [comment]
...it can currently only do binning `[ Process > Bin ]` by whole numbers.

Going from 1.5  to 10 is thus not possible. you could go to 9 by down-sampling by a factor of 6.

**Comment by tischi** [comment]
@anorak94 could you please try it again and post here the **output in the ImageJ log window**?

**Comment by anorak94** [comment]
should i reinstall fiji and bpd2

**Comment by tischi** [comment]
> should i reinstall fiji and bpd2

always a good idea 😄 

after that, could you please try it again and post the output in the ImageJ log window?

thanks!!

**Comment by tischi** [comment]
Thanks!

1. Could you please also post the output of the ImageJ log window?
2. Which OS are you running on?

**Comment by anorak94** [comment]
I am running on mac m1. I tried the same thing on ubuntu too but not after you asked me to reinstall

**Comment by tischi** [comment]
ok! I am running on a Mac, too. 
And what about the log window output?

**Comment by anorak94** [comment]
<img width="1217" alt="Screenshot 2021-06-30 at 11 42 57" src="https://user-images.githubusercontent.com/45297533/123939373-5dfc3c00-d998-11eb-8ee6-fd4e2c3ff76a.png">

**Comment by tischi** [comment]
@anorak94 I can reproduce the bug now! I am super sorry as I was trying to reproduce this on the wrong git branch the whole time. Thank you for staying tuned! I will work on it asap!

**Comment by tischi** [comment]
@anorak94 I uploaded a new version. If you restart Fiji it should update the plugin. Does it work?

**Comment by anorak94** [comment]
yes it works now thanks a lot
