### ISSUE TITLE
macro changing name & conv to 8 bit

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#173]
Hi All, I`m trying to use the RECORD function to create a macro for running the program on multiple dataset (from Luxendo raw data to downsampled/8bit/renamed TIFF files); it works quite well, but I face 2 issues: 1) not changing name of channels: If I ask to change the name of channels, when running the macro, a window asking to change the name of the volume appears and importantly, the name of the channels is not changed in the output files (even if “ channles name” is selected); 2) not converting to 8 bit adopting the desired 0-255 values: If I ask to convert to 8-bit and set min and max value, those values are not saved and the conversion is made using the default values displayed when opening the “convert to 8 bit” window;

I attach the error that I get when I run the macro and also copy below the the macro I try to run; do you have any suggestion about what I m doing wrong? ...Thanks! Alessandro

run("BDP2 Open Position And Channel Subset...", "viewingmodality=[Show in new viewer] directory=[D:\\PROCESSING\\210803_test_macro_BDP2\\kenzo_small_dataset\\raw] enablearbitraryplaneslicing=false regexp=[.*\\/stack_0_(?<C1>channel_.*)\\/(?<C2>Cam_.*)_(?<T>\\d+)(|.lux).h5] channelsubset=[channel_0_obj_left_Cam_Left,channel_0_obj_right_Cam_Right] ");
run("BDP2 Set Voxel Size...", "inputimage=[raw] outputimagename=[raw] viewingmodality=[Show in current viewer] unit=[µm] voxelsizex=0.541 voxelsizey=0.541 voxelsizez=2.0 ");
run("BDP2 Rename...", "inputimage=[raw] channelnames=[Ch0_Cam0,Ch0_Cam1] ");
run("BDP2 Bin...", "inputimage=[raw] outputimagename=[raw-bin] viewingmodality=[Show in new viewer] binwidthxpixels=4 binwidthypixels=4 binwidthzpixels=4 ");
run("BDP2 Convert to 8-Bit...", "inputimage=[raw-bin] outputimagename=[raw-bin-8bit] viewingmodality=[Show in new viewer] mapto0=[11.0,0.0] mapto255=[484.0,474.0] ");
run("BDP2 Save As...", "inputimage=[raw-bin-8bit] directory=[D:\\PROCESSING\\210803_test_macro_BDP2\\BDP2\\] numiothreads=1 numprocessingthreads=32 filetype=[TIFFVolumes] saveprojections=false projectionmode=[sum] savevolumes=true tiffcompression=[None] tstart=0 tend=1 ");

![error_w_macro](https://user-images.githubusercontent.com/35956783/128219718-f891a433-68d3-47c7-97b1-d1aecc98843e.JPG)

**Comment by tischi** [comment]
Looks like a bug that I need to fix, but I think you can try a work-around:

```
run("BDP2 Convert to 8-Bit...", "inputimage=[raw-bin] outputimagename=[raw-bin-8bit] viewingmodality=[Show in new viewer] mapto0=[11,0] mapto255=[484,474] ");
```

I just removed the decimal places in the `mapTo`...

Does that work?

**Comment by cikus3** [comment]
Hi Tischi, thanks, I ve removed the decimals and now no errror is showing up and it applies the value requested!

**Comment by tischi** [comment]
@cikus3 I uploaded a new version where it should now also work with the decimals.
