### ISSUE TITLE
macro 8bit conversion and change in channels names

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#174]
Hi Tischi, unfortunately I still have some comments/issues on how to make a macro aimed to covert images to 8 bit and change  channel names;  
first of all, thanks for the changes on the new BDP2 vesion;It works now if I type in the macro the values with decimals for specifying the values to be assigned as 0 and 255 in the 8 bit conversion ;

However, when I record a macro and convert to 8 bit, the values for 0 and 255 that are recorded in the macro are not the ones I type/select but the default ones (measuered by BDP2, I suppose); I can manually change them afterwards, but it would help to have already the correct ones in the macro text;

More importantly, when I record a macro for changing the name of the channels and using ““Channel naming scheme> channels names”, the new names are recorded in the macro text, but are not applied to the saved imaged; even if I type new channels names in the macro, the “channel index” and not “channel names” are selected and I keep seeing the old/default names of the channels. 

Also, when I run the macro in which I ask to change the channel names, BDP2 is asking me to insert the new name of the image (something I didn`t ask to change..). 

Any suggestions to overcome these issues?.. Thanks!

**Comment by tischi** [comment]
@cikus3 I was on holidays, but will try to look into those issues this week!

**Comment by tischi** [comment]
@cikus3 Thanks a lot for reporting all those bugs. I think I fixed all of them and uploaded a new version. It would be great if you could test it and let me know how it goes now! Thanks a lot!!

**Comment by cikus3** [comment]
Thanks, I`m actually going on holiday now.., but I`ll carefully test the new updates I`m back!

**Comment by cikus3** [comment]
Hi Tischi, happy to tell you that (it took me while.. ) but now when I use the macro created with BDP2 I can do the name change and 8bit conversion without any issue! Thanks again
