### ISSUE TITLE
Image metadata from first stack/channel i multi-stack/channel HDF directory

### ISSUE THREAD

**Issue by bondaren** [bigdataprocessor/bigdataprocessor2#181]
When Luxendo HDF file directory is provided as input, image dimensions of the first stack/channel are used regardless of the selection.

**Comment by tischi** [comment]
@bondaren could you please elaborate this a bit? for example, what you do exactly mean by image dimensions?

**Comment by tischi** [comment]
In fact, I had a look and, indeed, I am just looking at the first file to determine: nX, nY, nZ as well as the voxel sizes. 

Which of those quantities are you referring to? 

And, to be honest, I was not aware that any of those numbers could change within one "experimental microscope setup". 

I think to understand this I would need an example of the file and folder structure that you are dealing with and how the data was exactly acquired. Could you post and example here?

**Comment by bondaren** [comment]
Hi @tischi. The data is a bit too big to share here, but I will describe it. I have a dataset where channels differ by Z-step. E.g. "Stack_0_channel_0" sub-folder has images with voxel size 0.295x0.295x1 um whereas "Stack_0_channel_1" is 0.295x0.295x2 um. This is usually not the case, but depends on the experiment and can be beneficial sometimes. The data is from the SPIM. I didn't notice how the plugin behaves with image dimensions, though. If one has multiple views, the XY may also differ from stack to stack. E.g. Stack_0_channel_0 will be 2000px x 2000px whereas orthogonal Stack_1_channel_0 can be 2000px x 1000px, etc. Again, it will depend on a particular experiment/acquisition range.

**Comment by bondaren** [comment]
I think it can be sufficient if the user can get some error if dimensions do not match between stacks and/or channels, and then (ideally) have the option to read all channels/stacks separately, equilibrate manually, and combine in BDP2.  Maybe there is a smarter way around. For now, I restructure my folders for that 😺

**Comment by tischi** [comment]
@bondaren 
Thanks for the information!

I cannot open channels together that has different dimensions, this would be too much of a change in the whole software design. But I think I will try to implement the following (as a start):

- [ ] Upon loading inspect the dimensions of all the _selected_ channels
- [ ] Throw an error message if the dimensions do not match.

**Comment by bondaren** [comment]
Hi @tischi. Pls have a look here:
[example.zip](https://github.com/bigdataprocessor/bigdataprocessor2/files/7696894/example.zip)

**Comment by tischi** [comment]
Thanks!

When you try to open both channels it will now throw an error:

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: The channels are not consistent in their dimensionality (XYZ). Please see ImageJ Log Window for details.
	at de.embl.cba.bdp2.open.fileseries.FileInfosHelper.initFileInfos5D(FileInfosHelper.java:258)
	at de.embl.cba.bdp2.open.fileseries.FileInfosHelper.setFileInfos5D(FileInfosHelper.java:52)
	at de.embl.cba.bdp2.open.fileseries.FileInfos.fetchFileInfos(FileInfos.java:162)
	at de.embl.cba.bdp2.open.fileseries.FileInfos.<init>(FileInfos.java:130)
	at de.embl.cba.bdp2.BigDataProcessor2.openHDF5Series(BigDataProcessor2.java:177)
```

In the log window it will print:

```
# Metadata channel Channel_1_Cam_Fused
Folder: /Users/tischer/Documents/bigdataprocessor2/src/test/resources/test/luxendo-different-stack-size/
FileType: Luxendo HDF5
BitDepth: 8
nX: 528
nY: 1044
nZ: 26
nC: 2
nT: 1
voxelUnit: pixel
voxelSizeX: 1.0
voxelSizeY: 1.0
voxelSizeZ: 1.0
GB: 0.028664064
 
# Metadata channel Channel_2_Cam_Fused
Folder: /Users/tischer/Documents/bigdataprocessor2/src/test/resources/test/luxendo-different-stack-size/
FileType: Luxendo HDF5
BitDepth: 8
nX: 528
nY: 1044
nZ: 52
nC: 2
nT: 1
voxelUnit: pixel
voxelSizeX: 1.0
voxelSizeY: 1.0
voxelSizeZ: 1.0
GB: 0.057328128
```

Such that one can see what the issue is.

When opening only a subset of the channels it will only fetch metadata from the selected ones.

I think that fixes it?!

**Comment by bondaren** [comment]
Awesome! Thanks, Tishi!

**Comment by tischi** [comment]
I uploaded the changes to the Fiji update site.

Could you please test it?

**Comment by bondaren** [comment]
It tested with the full dataset and it works.
i) I can now choose channels separately with the correct metadata.
Iii) If I choose both with different metadata, I get the message:

# Metadata channel Channel_1_Cam_Fused
Folder: Z:\EMBRYOS\fused\
FileType: Luxendo HDF5
BitDepth: 16
nX: 1024
nY: 2048
nZ: 110
nC: 2
nT: 51
voxelUnit: pixel
voxelSizeX: 1.0
voxelSizeY: 1.0
voxelSizeZ: 1.0
GB: 47.06009088
 
# Metadata channel Channel_2_Cam_Fused
Folder: Z:\EMBRYOS\fused\
FileType: Luxendo HDF5
BitDepth: 16
nX: 1024
nY: 2048
nZ: 220
nC: 2
nT: 51
voxelUnit: pixel
voxelSizeX: 1.0
voxelSizeY: 1.0
voxelSizeZ: 1.0
GB: 94.12018176

**Comment by tischi** [comment]
Cool! Thanks for reporting the issue and testing the solution.
