### ISSUE TITLE
Saving in macro pops up window

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#182]
May I ask you to adjust one thing in BDP2 for me? It is not really a bug, but rather annoying feature.
I want to run a macro over the files in the folder, but when it executes “Save as”, I get a pop-up menu asking for an output folder, despite that I provided such folder name as a function argument in my macro, e.g.:

run("BDP2 Save As…”, “inputimage=[MyImageName] directory=[/myPATH/ numiothreads=1 numprocessingthreads=16 filetype=[BigDataViewerXMLHDF5] saveprojections=true projectionmode=[max] savevolumes=true channelnames=[Channel index (C00, C01, ...)] tiffcompression=[None] tstart=0 tend=65”)

That pop-up menu does not allow executing commands automatically.
I am also not sure how I can close the windows to prevent naming confusions, but for that you seem to have a "current viewer” or "do not show” options.

**Comment by tischi** [comment]
@bondaren Thanks for reporting! I will fix this ASAP!
Meanwhile, could you please post here an actual macro that you are trying to run? 
The syntax of the `myPath` part does not seem quite correct to me...

**Comment by tischi** [comment]
#### Prevent images from showing

In the script:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/2157566/143834316-b0bc8812-9bc9-4647-80d0-9dc131af37e2.png">

See [this example](https://raw.githubusercontent.com/bigdataprocessor/bigdataprocessor2/master/scripts/rename-channels-silent.ijm).

#### Prevent window popping up during saving

I can reproduce that this happens when there is something wrong in the `directory` parameter. Then the script tries to resolve this by popping up the window. Could you please paste your whole script here? In your example above there  is a `]` missing:  `directory=[/myPATH/ ` should be `directory=[/myPATH]`

**Comment by bondaren** [comment]
I think you're right. It looks like I was missing that "]" in the end: 	
command6 = "inputimage=[Cam_C8BB] directory=["+TargetDir+"stack_"+stack+"_channel_"+channel+"/ numiothreads=1 numprocessingthreads=16 filetype=[TIFFVolumes] saveprojections=true projectionmode=[max] savevolumes=true channelnames=[Channel names] tiffcompression=[None] tstart=0 tend="+maxt+" ";
run("BDP2 Save As...", command6);

This solved the problem, thanks!

However, in the meantime, I found that another pop-up menu is asking to select a viewer when i open the series:
![image](https://user-images.githubusercontent.com/46903200/143861795-19866e82-646a-479c-b28c-2626bced82d6.png)

Any idea why this could be the case?
Here is the code:
command1 = "iewingmodality=[Show in current viewer] directory=[" + SourceDir + "] enablearbitraryplaneslicing=false regexp=[.*\\/[sS]tack_" + stack + "_(?<C1>[cC]hannel_.*)\\/(?<C2>Cam_.*)_(?<T>\\d+)(|.lux).h5] channelsubset=[channel_" + channel +  "_Cam_Long] ";
run("BDP2 Open Position And Channel Subset...", command1);

**Comment by tischi** [comment]
Looks like another typo 😸 

`"iewingmodality=[Show in current viewer]`

should be

`"viewingmodality=[Show in current viewer]`

**Comment by bondaren** [comment]
I looked at this line 100x times and could not see it.. 😹
Perhaps, my confusion was that I was expecting the code to crash in case of typos, but things were running smoothly. 
I'll keep in mind now that it switches to a default behaviour instead.
Thanks a lot, Christian! Everything works now

**Comment by tischi** [comment]
> Perhaps, my confusion was that I was expecting the code to crash in case of typos, but things were running smoothly.

This is indeed a bit unfortunate. I also just learned this today....
