### ISSUE TITLE
Size of "rename" box

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#187]
The window/box that appears when channels name needs to be changed (see attach) can`t be enlarged (that makes difficult to read the text  -that is generally very long...); any possibility to make this window modifiable in size? Thanks!
![image](https://user-images.githubusercontent.com/35956783/152198897-c23f9e43-8b0f-435e-8f9a-4a9e28c4064f.png)

**Comment by tischi** [comment]
Thanks! I fixed it.
