### ISSUE TITLE
Add more Bio-Formats tests

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#196]
There currently is only one test for opening a file with Bio-Formats:

https://github.com/bigdataprocessor/bigdataprocessor2/blob/c576c214671e0d18753bea8445c9d62fa2108e79/src/test/java/test/open/TestOpenSingleChannelFloatTiffVolumeWithBioFormats.java#L53

@NicoKiaru would you have time to add some more tests? 

For example:

- [ ] A very small multi-channel .czi file
- [ ] A very small BDV/XML/HDF5 file

**Comment by smicro2020** [comment]
Hi, you can use these two:
Here is a 5-x cropped dataset acquired on Zeiss Lattice Lightsheet, a single time point, in a source format: https://drive.google.com/file/d/1I7KrLfdgnnDzFN2FhtsPMiWjZ_FFCgcJ/view?usp=sharing

Here is the same one after the deskew (with restored pixel geometry, as processed in ZEN software): https://drive.google.com/file/d/1am5wR75WAPo58L8nLbnuXMGit1-7vSSg/view?usp=sharing

**Comment by tischi** [comment]
Thanks @smicro2020! Did you add them here because there currently are some issues opening them?

**Comment by smicro2020** [comment]
You asked for the example, so I placed them here because they are typical .zvi files (both uncompressed). 

The issue with .zvi files I got that in BDP2, "Miscellaneous > Configure Lazy Loading" fails with an error "Cache cannot be replaced for image of class: VolatileCachedCellImg"

**Comment by tischi** [comment]
Thanks for the clarification! I will look into it.

**Comment by tischi** [comment]
Hi @smicro2020,

I can confirm that BDP2 can open both the files that you provided. 

So we can use them to add more tests.

I also confirm that trying to change the caching is throwing an error => I fixed this.
