### ISSUE TITLE
Macro does not record  Misc -> Show in Hyperstack Viewer...

### ISSUE THREAD

**Issue by ehudsivan** [bigdataprocessor/bigdataprocessor2#201]
Hi
We would like to switch programmatically (Fiji macro) from the BDP2 viewer to the FIji built in Hyperstack viewer. We can do it via the user interface. However, the recording only records the SelectImage("Title within BDP2 Viewer") command, and unfortunately, the "Title within BDPW Viewer" is not recognizable in the FIji macro as an image title.

**Comment by tischi** [comment]
Hi @ehudsivan, interesting! 

I guess you then would like to continue the analysis with IJ-Macro in the "normal Fiji"?

**Comment by ehudsivan** [comment]
Exactly, this way we would be able, for example, to crop a big data image using BDP2 and then continue the analysis using regular macro commands.

**Comment by tischi** [comment]
This makes a low of sense! I will look into recording the command in a better way!

**Comment by tischi** [comment]
working on this here: https://github.com/bigdataprocessor/bigdataprocessor2/pull/203

**Comment by tischi** [comment]
@ehudsivan I uploaded a new version of BDP2, where this works on my computer:

```
run("BigDataProcessor2");
run("BDP2 Open Custom File Series...", "viewingmodality=[Show in new viewer] enablearbitraryplaneslicing=false directory=/Users/tischer/Documents/bigdataprocessor2/src/test/resources/test/tiff-nc2-nt6-subfolders fileextension=.tif regexp=(?<C>.*)/.*T(?<T>\\d+) hdf5datasetname=Data");
run("BDP2 Set Voxel Size...", "inputimage=[tiff-nc2-nt6-subfolders] outputimagename=[tiff-nc2-nt6-subfolders] viewingmodality=[Show in current viewer] unit=[µm] voxelsizex=1.0 voxelsizey=1.0 voxelsizez=1.0 ");
run("BDP2 Rename...", "inputimage=[tiff-nc2-nt6-subfolders] outputimagename=[im] viewingmodality=[Show in new viewer] channelnames=[a,b] ");
run("BDP2 Save As...", "inputimage=[im] directory=[/Users/tischer/Desktop/bdp2-out/] numiothreads=1 numprocessingthreads=4 filetype=[TIFFVolumes] saveprojections=true projectionmode=[sum] savevolumes=true channelnames=[Channel names] tiffcompression=[None] tstart=0 tend=5 ");
run("BDP2 Show as Hyperstack...", "inputimage=[im] ");
```

Notice the last line in the above macro code.

Does this work for you?

**Comment by ehudsivan** [comment]
Looks great. thank you for the quick turn around
