### ISSUE TITLE
FIJI macro doesn't work properly

### ISSUE THREAD

**Issue by smicro2020** [bigdataprocessor/bigdataprocessor2#204]
Hi all, BDP2 brings an outstanding possibility to deskew Zeiss lattice lightsheet images in real time. I recorded a super simple macro that works (smi_deskew, it is .ijm). 
1. Then I place it in the \macros\AutoRun folder to launch automatically with Fiji, but it fails. 
I placed it on a button in a tool menu, Fiji.app\macros\toolsets, and it failed, with different errors on the first and subsequent launches (see a single button example smi-LLS.testTools and it is .ijm). 
Any help would be very appreciated! 
2. This is a question and not a bug: 
I now export the binned and deskewed view to the FIJI hyperstack at the end. A more suitable option is to use BigDataViewer and orthogonal slices there instead, but I need help finding a way to pass data from BDP2 to BigDataViewer processing without loading the entire dataset. Thanks in advance for your help.
upd: FIJI is up to date, OS Windows10
[smi_deskew.txt](https://github.com/user-attachments/files/16648140/smi_deskew.txt)
[smi-LLS testTools.txt](https://github.com/user-attachments/files/16648141/smi-LLS.testTools.txt)

**Comment by tischi** [comment]
Dear @smicro2020,

Thank you very much for raising this issue. 

I was on holidays and thus only saw this now. 

I will try to look into this next week.

Do you by chance have a small example image data set that you could provide for download such that I could reproduce this?

**Comment by smicro2020** [comment]
Hi, sorry for the late response; I was also on holiday. I uploaded a 5-x cropped image, single time point, in a source format:  [https://drive.google.com/file/d/1I7KrLfdgnnDzFN2FhtsPMiWjZ_FFCgcJ/view?usp=sharing](url)

Here you can find a deskewed one (with restored pixel geometry, as processed in ZEN software): [https://drive.google.com/file/d/1am5wR75WAPo58L8nLbnuXMGit1-7vSSg/view?usp=sharing](url)

Thank you very much for your help! My real datasets are 20-70Gb each, so it is challenging to see them, especially as a movie.

**Comment by tischi** [comment]
Thanks @smicro2020!

Indeed, placing the macro in `/macros/AutoRun` and then starting Fiji yields:

```
[ERROR] Command errored: BDP2 Show as Hyperstack...
java.lang.NullPointerException
	at de.embl.cba.bdp2.utils.Utils.setCalibration(Utils.java:567)
	at de.embl.cba.bdp2.utils.Utils.asImagePlus(Utils.java:476)
	at de.embl.cba.bdp2.misc.ShowAsHyperstackCommand.show(ShowAsHyperstackCommand.java:64)
	at de.embl.cba.bdp2.misc.ShowAsHyperstackCommand.run(ShowAsHyperstackCommand.java:59)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

Are you getting the same error? I will look into it....

**Comment by tischi** [comment]
Could you please use the below macro instead within the `AutoRun` folder? For me this works now. The main change, I think, is that in the line where you are setting the voxel size I am now using the term `micrometer` instead of `µm`. Why this actually may solves the issue I honestly have no idea 😅 

```
macro "Open zvi and deskew bin 3" {

	//open("C:/Fiji/Fiji.app/jars/bigDataProcessor2-1.7.0.jar");
	voxelbin = 3;
	//run("BigDataProcessor2"); // you don't need this for running from a macro
	path = File.openDialog("Select a File");
	getDateAndTime(year, month, dayOfWeek, dayOfMonth, hour, minute, second, msec);
	print("Started: ", hour, minute, second, msec);
	dir = File.getParent(path);
	name = File.getName(path);
	nameshort = File.getNameWithoutExtension(path);

	run("BDP2 Open Bio-Formats...", "viewingmodality=[Show in current viewer] enablearbitraryplaneslicing=true file="+path+" seriesindex=0");
	run("BDP2 Affine Transform...", "inputimage=["+nameshort+"] outputimagename=["+nameshort+"-transformed] viewingmodality=[Show in current viewer] affinetransformcsv=[1,0,0,0,0,0.5,0,0,0,0.707106781,1,0] interpolation=[Linear] ");
	run("BDP2 Set Voxel Size...", "inputimage=["+nameshort+"-transformed] outputimagename=["+nameshort+"-transformed] viewingmodality=[Show in current viewer] unit=[micrometer] voxelsizex=0.15 voxelsizey=0.15 voxelsizez=0.15 ");
	run("BDP2 Bin...", "inputimage=["+nameshort+"-transformed] outputimagename=["+nameshort+"-bin] viewingmodality=[Show in current viewer] binwidthxpixels="+voxelbin+" binwidthypixels="+voxelbin+" binwidthzpixels="+voxelbin+" ");
	getDateAndTime(year, month, dayOfWeek, dayOfMonth, hour, minute, second, msec);
	print("Transformed: ", hour, minute, second, msec);
	run("BDP2 Show as Hyperstack...", "inputimage=["+nameshort+"-bin] ");
	getDateAndTime(year, month, dayOfWeek, dayOfMonth, hour, minute, second, msec);
	print("Hyperstack: ", hour, minute, second, msec);
	// image>stack>view5D for slicer (slow)
  }
```
------

Regarding your second question: I don't really understand: if you simply do *not* export as a hyperstack you have the image open in BigDataViewer and can use `Shift X, Shift Y, Shift Z` to inspect the image in orthogonal directions...

<img width="912" alt="image" src="https://github.com/user-attachments/assets/13ded0a8-ce42-4c9e-b170-b696d4b6c849">
<img width="912" alt="image" src="https://github.com/user-attachments/assets/ea312dba-eae2-4f09-a638-c6a9d0891846">
<img width="912" alt="image" src="https://github.com/user-attachments/assets/8588b25e-174f-43d0-a45e-a4c264117cca">

**Comment by tischi** [comment]
> And one more issue with this data type: I can't Configure Lazy Loading, it causes an error:

Dear @smicro2020, I am not sure what you mean here. 

Since this issue is closed now, may I please ask you to open a new issue with all details needed to reproduce the error.

General comment: Please raise several issues, one for each problem, this makes it much easier for everyone to keep track. Issues should not be used as chat channels ;-)
