### ISSUE TITLE
tracking

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#41]
If you find the time, could you try to use the code from here for the tracking?

https://github.com/embl-cba/fiji-plugin-bigDataProcessor/tree/master/src/main/java/de/embl/cba/bigdataprocessor/track

- CenterOfMassTracker
- CorrelationTracker

Just copy and paste. You'll have to replace the `getDataCube` functions by `Views.interval`.

**Comment by ASHISRAVINDRAN** [comment]
Hi Tischi,
I need clarification here! :)
I had a detailed look into the `bigDataProcessor` tracking code for the Center of mass/Correlation tracking. This seems to be the refactored version of the `ObjectTracker.java` from the `bigDataTools` times.
This code is in Imglib1 and in the current `bigDataProcessor2` repo, we have imglib2 based code. (The migration was done in Oct-Nov, 2018)
I am confused now-- why should we migrate the same code again to imglib2? 
I understand that `bigDataProcessor2` currently doesn't have the features like track table, image filters etc.
Hence by asking to use the code from `bigDataProcessor`, you mean to go forward with the implementation of missing features referring to the above-mentioned code base, right?

**Comment by tischi** [comment]
I mean just the actual tracking code. To go from imglib1 to imglib2 my feeling is that, as mentioned, you only need to "replace the `getDataCube` functions by `Views.interval`. 
But maybe to complex without talking, do you maybe have time to pass by this month?

**Comment by tischi** [comment]
We implemented manual tracking for now.
Thus closing the issue.
