### ISSUE TITLE
SelectionBoundingBox Overlay freezes

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#44]
Sometimes functionality that requires overlay of the selection bounding box freezes.
We do not know at which line of the code this happens...

**Comment by tischi** [comment]
Probably it clashes with the grayvalue overlay. We disabled this for now.

**Comment by ASHISRAVINDRAN** [comment]
Hi Tischi,
There is a hack with which we can successfully render and use the cropping selection box without freezing while testing/debugging.
The trick is to keep a debug point on one of the last lines of `bdv.tools.boundingbox.TransformedRealBoxSelectionDialog` class constructor. (Class part of `bigdataviewer-core-6.0.0-sources` jar)
Once the program execution comes to that line of code, simply walk through another line or so before pressing "Resume program execution" (I am using IntelliJ). 
This helped to suppress the issue all the time today, rather than counting on luck for the selection box to be rendered properly. :)
I don't know why this works.  Does it ring a bell to you?
Anyway, this helps me code and test BigDataTracker functionalities smoothly.

**Comment by tischi** [comment]
@ASHISRAVINDRAN Do you remember a way to force the hanging issue to happen? It happened several times last week during a course I was teaching, but now I cannot make it happen on my computer...

**Comment by tischi** [comment]
related to: https://github.com/bigdataviewer/bigdataviewer-core/issues/77#issuecomment-577634078

**Comment by ASHISRAVINDRAN** [comment]
I am not sure how to force the hanging issue to happen. It was almost always happening when I was working on the repo last year. Currently, I have a local repo version at this commit 625bc93a689dc61d3c14b966e2da244d4ca41dd9. Here, the bounding box seems to hang when I test now.
Maybe you can make a git checkout at this commit (or any other commits around the time we had this issue) point and run again to replicate the issue.

**Comment by tischi** [comment]
@ASHISRAVINDRAN 
I made a new branch called **testCropFreeeze**; inside this branch there is a class in `src\test\explore`, called `ExploreCropFreeze`. For me, it does not freeze...

1. Could you please test whether it freezes for you?
2. And, if it freezes, could you please try to find out where it freezes using this approach? https://github.com/bigdataviewer/bigdataviewer-core/issues/77#issuecomment-577634078
3. If that does not freeze for you, could you tell me how you make it freeze?

Thanks a lot!

**Comment by ASHISRAVINDRAN** [comment]
Hi @tischi 
1. I cloned the **testCropFreeeze** branch and ran `ExploreCropFreeze` file. It didn't freeze for me too. In general, this freezing is an indeterministic event. I ran many times, it never froze. However, when I ran complete workflow: opening UI, opening the files and manually selecting crop option from the menu, freezing instances **appeared**, finally. But, most of the times it didn't freeze. (_I was recollecting the times when this freezing was really annoying and wanted to fix it somehow. I don't know what changed now!_)
2. I profiled a couple of frozen sessions using VisualVM as in the bigdataviewer issue comment link. The VisualVM showed no DEADLOCK warning message though. The AWT-EventQueue-0 seemed BLOCKED. The point is freezing/WAITING is in `pool-1-thread-1` at:
```
bdv.tools.boundingbox.AbstractTransformedBoxSelectionDialog.getResult(AbstractTransformedBoxSelectionDialog.java:121)
	- locked <0x00000000dc5877b0> (a java.lang.Object)
```
The code at line 121 is ```setVisible( true );```
Attaching the thread dump herewith.
[threaddump-1584477348906.txt](https://github.com/tischi/fiji-plugin-bigDataProcessor2/files/4345925/threaddump-1584477348906.txt)

3. I don't have any solid pathway/workflow to replicate the freezing issue. Running manually helped even though I had to re-run many times. Sometimes it froze in the first or second run, sometimes had to re-run many times.

Hope this helps!

**Comment by tischi** [comment]
Thank you very much for testing! I send a mail to @tpietzsch pointing him to this issue. I hope he has an idea.

I have one suspicion: Maybe when there is a lot of logging going, this could lead to the freeze. Could you try adding more `Logger.log("aaaaaa")` at some places to see whether this makes it worse?

**Comment by tischi** [comment]
@ASHISRAVINDRAN 
I found this on the internet: https://www.javaspecialists.eu/archive/Issue101.html
This looks very similar. If you have some time, could you see whether adding `SwingUtilities.invokeLater()` at some place makes the problem go away? I would also test it, but it almost never happens to me (seems some difference between Mac and Win).

**Comment by tpietzsch** [comment]
I would try to add `SwingUtilities.invokeLater()` here:
https://github.com/bigdataviewer/bigdataviewer-core/blob/9c30aa850c27e8727cf4f71d49945e37eef0d443/src/main/java/bdv/tools/boundingbox/AbstractTransformedBoxSelectionDialog.java#L121

`SwingUtilities.invokeLater( () -> setVisible( true ) );`

**Comment by tischi** [comment]
@ASHISRAVINDRAN 
To test this you would have to 
1. clone bigdataviewer-core: https://github.com/bigdataviewer/bigdataviewer-core
1. change above line of code in bigdataviewer-core
1. `mvn clean install` bigdataviewer-core
1. in our code, in the pom.xml add the version:
```
		<dependency>
			<groupId>sc.fiji</groupId>
			<artifactId>bigdataviewer-core</artifactId>
			<version>8.0.1-SNAPSHOT</version>
		</dependency>
```

Do you think you could try this?

**Comment by ASHISRAVINDRAN** [comment]
Hi @tischi 
I tried this yesterday itself using Bigdataviewer-core version 6  (because that was the version around the time we first had the issue and hence compliant the last commit of **testCropFreeeze** branch ). I had that repo in my archives. 
The result is that all the tests are now working **fine**! **No** more frozen sessions. So I think this has solved the issue!

I also tried adding ```SwingUtilities.invokeLater()``` at the _BdvMenus.java_. Instead of calling the cropping functionality (inside `actionPerformed`) using executer service, I replaced with this:
```SwingUtilities.invokeLater(() -> new Cropping<>( imageViewer ));```
This **doesn't work** at all. The slider bars and buttons on the dialog box never showed up.


For the sake of the record, I will also test using bigdataviewer-core: 8.0.1-SNAPSHOT jar and update later.

**Comment by tischi** [comment]
> The result is that all the tests are now working fine!

You mean **_after_** including: `SwingUtilities.invokeLater( () -> setVisible( true ) );` in bigdataviewer-core?

> I also tried adding SwingUtilities.invokeLater() at the BdvMenus.java. Instead of calling the cropping functionality (inside actionPerformed) using executer service, I replaced with this:
SwingUtilities.invokeLater(() -> new Cropping<>( imageViewer ));

I tried this as well with the same result: this always hangs immediately.

**Comment by ASHISRAVINDRAN** [comment]
> You mean **_after_** including: `SwingUtilities.invokeLater( () -> setVisible( true ) );` in bigdataviewer-core?

Yes!

**Comment by tpietzsch** [comment]
> `SwingUtilities.invokeLater(() -> new Cropping<>( imageViewer ));`
> This **doesn't work** at all. The slider bars and buttons on the dialog box never showed up.

Yes, that is to be expected.
The thread calling `TransformedBoxSelectionDialog.getResult()` is blocked until the result is available (the dialog is closed). And if that calling thread is the AWT thread, well ...

> > You mean **_after_** including: `SwingUtilities.invokeLater( () -> setVisible( true ) );` in bigdataviewer-core?
> 
> Yes!

Cool, thanks for testing!!! I'll fix that in the next release.

**Comment by tischi** [comment]
works now
