### ISSUE TITLE
ChromaticShiftCorrection

### ISSUE THREAD

**Issue by metavibor** [bigdataprocessor/bigDataProcessor2#52]
When I click on chromatic shift correction nothing happens?

**Comment by tischi** [comment]
Yes, very true!
Can you please update and try again?
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2157566/57442685-c3d35a00-724c-11e9-9f3f-039d7870f144.png">

**Comment by metavibor** [comment]
Thank you!
Now I get the interface however there is a rather annoying behavior that prevents the use of this tool - every time one clicks  on the arrows to shift the respective channels the BigDataViewer resets to the "default" view. So after spending some minutes to adjust brightness of two channels and locating the respective objects in 3D space, everything is lost (brightness is reseted as well as the x, y, z, and the zoom) the moment one clicks on one of the arrows 
Also, once one selects the ChromaticShiftCorrection tool (or Bin tool) a new instance of BigDataViewer is started, is this intended?

**Comment by tischi** [comment]
> every time one clicks on the arrows to shift the respective channels the BigDataViewer resets to the "default" view.

Thanks for point this out! I will look into this! I think I should be able to fix this....

**Comment by tischi** [comment]
The view is preserved now, there still is a short flickering, though.
See here: https://github.com/bigdataviewer/bigdataviewer-vistools/issues/32

**Comment by tischi** [comment]
> brightness is reseted as well 

I fixed this as well. Please check whether it works for you. The values in the B&C dialog of Bdv are wrong however, don't know how to fix this...
See here: https://github.com/bigdataviewer/bigdataviewer-vistools/issues/33
