### ISSUE TITLE
ImageJ Viewer

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#67]
I  still prefer the ImageJ Viewer than the BDV viewer; it is more intuitive and friendly (for old school Fiji people..). It would be ideal if by default it would be opened

**Comment by tischi** [comment]
This is unfortunately too much work. But I can try to make BDV more user friendly.
What is the main thing that you would like to see there?

**Comment by cikus3** [comment]
I m getting familiar with BDV..However,  what I like in FIJI viewer is: the Auto display in the B/C control window, the fact you can do (for some files) Z-projections and use basic FIJI options (such as make measures).

**Comment by cikus3** [comment]
Great, very useful the Hypersatck viewer! It seems that is even faster sometimes than the BDViewer....
