### ISSUE TITLE
browser kept open for multiple images

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigDataProcessor2#68]
what I liked from the old BDT  is that once one dataset was opened, the browsers-window  (with same settings) was still open and it could be used to quickly open multiple files;

**Comment by tischi** [comment]
This should now also be the case for the new one. You have to select: Open in new viewer:
![image](https://user-images.githubusercontent.com/2157566/85290550-768a6a00-b499-11ea-8aac-dee43c548d21.png)
Does that work for you?

**Comment by cikus3** [comment]
Great! working nicely!
