### ISSUE TITLE
regular expressions help

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigDataProcessor2#69]
I like the "useful examples" in the pop up window; unfortunately, at least in Windows, it is not possible to copy and paste these values/texts; ideally, if the reg expression for Luxendo MuVi were loaded by default..it would be great

**Comment by tischi** [comment]
> if the reg expression for Luxendo MuVi were loaded by default..it would be great

done.

**Comment by tischi** [comment]
> unfortunately, at least in Windows, it is not possible to copy and paste these values/texts;

On a Mac I can highlight in the window and then copy and paste using the keyboard shortcut for this. Right click with the mouse does not work.... Did you try with the keyboard?

**Comment by cikus3** [comment]
Great! Very useful the MuVi Luxendo option; also, with the keyboard commands it works! Last thing: open the "Open custom" window I first need to close the " open custom Help"; if I could keep both windows open it would be even easier..Moreover, I still didn t manage to open the files resulting from Luxendo GUI processing (images fused, HDF5,..); a dedicated window to do it, would be super... The window "only matching" was also useful to selectively open a file in folders containing multiple files.
