### ISSUE TITLE
Huge memory requirement

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#70]
Converting large  dataset fom Luxendo raw data to TIFF , I`ve noticed that the memory keeps being utilized/increasing and at the end I was at 85% (of 128 GB or RAM!!); if there was a way to " clear" the memory after saving each stack, it would probably help to prevent the PC from crashing;

**Comment by luxendo-support** [comment]
It appears like the BDP2 doesn't deallocate the RAM after a processing job. Had the same issue when saving files in IMS format.

**Comment by tischi** [comment]
Did you ever observe a crash?

**Comment by cikus3** [comment]
Not tried yet to save big files..However, when I had this issue (1 month ago) FIJI  usually was not crashing, but just get stuck;

**Comment by tischi** [comment]
I made some changes in the code such that it would consume less memory.
Please try again from tomorrow on.

**Comment by cikus3** [comment]
I tried to use the new BPP2 to save same volumes of a big time lapse (about 1TB) and I ve noticed that the memory was increasing till 70% (of 128 GB) during the processing... I have the feeling that it is still not clearing the memory after each volume saving;

**Comment by tischi** [comment]
@cikus3 

ok!

1. but at least it was not crashing, was it? 
2. and it just less memory than the 1TB, indicating that it does clear the memory from time to time?

**Comment by tischi** [comment]
@nicoKiaru
It looks like I am having issue with a memory leak using `CachedCellImg` in imglib2. It could of course also be something else.
I think you found out some stuff recently, isn't it? Could you summarise the outcome for me or point me to the discussion?

**Comment by NicoKiaru** [comment]
My take on these memory leaks: 

Generally speaking two tools you need to have:
* https://visualvm.github.io/
With this you can see the memory usage, threads, make heap 'dumps'

* https://www.eclipse.org/mat/ 
With this you can analyze and find in details the source of the leaks

Both visualvm and mat are standalone. No need to build your project on eclipse

This 1 hour video is really worth watching:
* https://www.youtube.com/watch?v=_CruQY55HOk

It's for android but still valid for the concepts and tools it presents. You can make the heap dumps with visualvm instead of the android stuff.

For the imglib2 specific stuff:
- In my case, I switched from `DiskCachedCellImg` from `ReadOnlyCellImg` (it was ok for my use case) : with `DiskCachedCellImg` there were some IO threads that were never closed : they keep some references on the source alive and thus cannot be collected. Keeping track of these IO threads was difficult, so the read only option was better

- I forgot to call bdv.close() -> important to release some resources

- I had custom listeners which were holding references on unrelated objects

To find this, I was just opening an image calling GC (you can click on the ImageJ window), then removing the image, calling GC. If the memory was not back to its original level, then most probably I had a leak remaining.

Hope that helps, good luck because it's necessary but quite a pain!

**Comment by tischi** [comment]
@NicoKiaru 
Thanks so much! 
Do I understand it right that if one calls `System.gc()` and if there is no immediate effect there likely is an issue, right?

**Comment by NicoKiaru** [comment]
Most probably yes. 

You have the used memory on the IJ bar when you click (or double click) on it (it also calls GC):
![image](https://user-images.githubusercontent.com/20223054/93989570-5a44e480-fd8a-11ea-96bb-f4f37f49e525.png)

Here only 50MB is used - that's for a standard 'empty' ImageJ.

Clicking on the IJ bar is an easy way to keep track of the used memory.

Now of course if you are actively working on something you'll have a big amount of the memory used. You'll realise there's a leak when you close all your images and there's still like 800Mb occupied in RAM.

**Comment by tischi** [comment]
hmmm, I am using this already:

```
 final CachedCellImg cachedCellImg =
                new ReadOnlyCachedCellImgFactory().create(
                    loader.getDimensions(),
                    fileInfos.getType(),
                    loader,
                    options);
```
So it probably is something else.

**Comment by NicoKiaru** [comment]
Are you using `SoftRef` in your cache options ? But if you do not have an obvious suspect, eclipse mat will help you for the investigation

**Comment by tischi** [comment]
> Are you using `SoftRef` in your cache options ? But if you do not have an obvious suspect, eclipse mat will help you for the investigation

Not sure. I am doing like this:
```
final ReadOnlyCachedCellImgOptions options = options().cellDimensions( loader.getCellDims() );
```

**Comment by tischi** [comment]
...In the memory critical part of the application I even add  `.maxCacheSize( 0 ); ` hoping that this helps.

**Comment by NicoKiaru** [comment]
I think the default is `SoftRef`. MaxCacheSize is ignored in this case, you can have a look in the builder of  `CacheOptions`, it's well explained.

It can also be totally unrelated - you should start by making a thread dump with visualvm and `Find GC Roots` of an object which should have disappeared to find out what is retaining it from being GCed. Eclipse Mat does also that in a better way.

**Comment by tischi** [comment]
Oh, wow! Good to know! Looks like I need the `Bounded` type. What irritates me is that the `CacheType` enum is part of `DiskCachedCellImgOptions`, indicating that it would only be used for that?! 
How is caching handled for the `ReadOnlyCachedCellImg`? Does it still apply?

```
final ReadOnlyCachedCellImgOptions options = options()
                .cellDimensions( loader.getCellDims() )
                .cacheType( DiskCachedCellImgOptions.CacheType.BOUNDED )
                .maxCacheSize( 0 );
```

**Comment by tischi** [comment]
...I just checked and the `DiskCachedCellImgOptions.CacheType` also is used in the `ReadOnlyCachedCellImg`. Maybe should be factored out into an own class...

**Comment by cikus3** [comment]
Can`t help you in this discussion…but thanks for the work you are doing!
In my experience, the system was not crashing, just slowly increasing the  amount of RAM used;
Alessandro

---
Alessandro Ciccarelli
Light Sheet Specialist
CALM - Crick Advanced Light Microscopy Facility
The Francis Crick Institute
1 Midland Road - London -NW1 1AT
United Kingdom

T: +442037960913
E: alessandro.ciccarelli@crick.ac.uk<mailto:alessandro.ciccarelli@crick.ac.uk>
W: www.crick.ac.uk<http://www.crick.ac.uk/>

**Comment by tischi** [comment]
> In my experience, the system was not crashing, just slowly increasing the  amount of RAM used;

Thanks, this is helpful to know and it fits above suspicion.

**Comment by cikus3** [comment]
I ve updated and tested some large saving; memory stable at 14-18% and not increasing with time; so thanks, issue solved (for may side!)!

**Comment by tischi** [comment]
Great! This may still vary a bit in terms of how much memory is exactly consumed, but I hope the fact that it is stable stays!
Thanks @NicoKiaru again!!

**Comment by NicoKiaru** [comment]
You're welcome @tischi, but what did you change ? Just curious

**Comment by tischi** [comment]
from softref to bounded.
