### ISSUE TITLE
progress bar 

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#72]
- the progress bar behaves quite strangely while saving the data ..It seems the % does not reflect the real progress; it was 0% for 90% of the time, and then it went to 50% and stop;

**Comment by tischi** [comment]
Come on, that's what progress bars do ;-)
But let me check!

**Comment by cikus3** [comment]
It is really not essential...However I did a quick conversion/saving some files and the bar jumped from 1 to 100%; not sure if it is really following the progress.

**Comment by cikus3** [comment]
Now it works, thanks!
