### ISSUE TITLE
name of output file and name of raw data

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#73]
While converting Luxendo Raw data to TIFF, the name to the stacks assigned from BDP2 is different from the name used to identify the Luxendo raw files; I know that that the naming scheme from Lux is quite complex, but if eh TIFF could maintain the Channel, Camera, Stack name it would help;

**Comment by tischi** [comment]
That is indeed a bit tricky, because the Luxendo channel information is distributed across folder and file name, e.g. "stack_11_channel_0/Cam_Left", but what I think I could do is, e.g.: "C0Left--T0001.tif" as output names. Would that help?

**Comment by tischi** [comment]
...I also changed the Rename command such that you can rename the channels. So then it could we whatever you like:
![image](https://user-images.githubusercontent.com/2157566/85288982-fc58e600-b496-11ea-93bb-49caf820ecb5.png)

**Comment by cikus3** [comment]
Thanks; I ve just noticed that in the new version, it easily possible to rename the images and the channels (that sometimes are instead just different views); however, when I saved the data in TIFF I see that new name is not kept; would it be possible to keep it also in the saved file?

**Comment by tischi** [comment]
see here: https://github.com/bigdataprocessor/bigDataProcessor2/issues/71

would you also like to have an option to use the channel names instead of `C00` and `C01`?

**Comment by cikus3** [comment]
yes, it would be nice!

**Comment by tischi** [comment]
I implemented this option for the Tiff Volume saving. 
Is this sufficient or do you also need it for other saving modalities?

**Comment by cikus3** [comment]
Wonderful, it works! At the moment is enough for saving Tiff volume;thanks!
