### ISSUE TITLE
Metadata not read from Luxendo files

### ISSUE THREAD

**Issue by luxendo-support** [bigdataprocessor/bigDataProcessor2#79]
the BDP2 doesn't read the voxelsize from the Luxendo HDF5 files. Instead it assumes 1x1x1 µm.

**Comment by tischi** [comment]
Thank you for letting me know. Could you provide me with one example file (as a download link) such that I can implement this? In addition, I think I heard that you also may have json files for the metadata? This would be even easier to parse for me...

**Comment by tischi** [comment]
works now (for the non-processed ones).
