### ISSUE TITLE
8-bit conversion

### ISSUE THREAD

**Issue by metavibor** [bigdataprocessor/bigDataProcessor2#90]
How does one do an 8-bit conversion with different settings for every channel? When I click on "convert to 8-bit" in the "processing" menu I only get options that take first channel into account

**Comment by tischi** [comment]
That is a very good point! 
Currently, it will convert all channels with the same mapping. 
It will be some work to make this for each channel separate.
How would you envision the user interface? 
Probably the whole thing multiple times for each channel?
![image](https://user-images.githubusercontent.com/2157566/87562924-e4077000-c6be-11ea-8d0d-9938c93c839e.png)

**Comment by metavibor** [comment]
yes, I think that will work.... connected to that - is it possible to measure px values in BDP2? to be able to convert I would like to know what is min/max/average px value in any particular slice or ROI

**Comment by tischi** [comment]
> is it possible to measure px values in BDP2? to be able to convert I would like to know what is min/max/average px value in any particular slice or ROI

I made a new issue for this => https://github.com/bigdataprocessor/bigDataProcessor2/issues/91

**Comment by tischi** [comment]
@metavibor 
Would that work for you? Suggestions for improvements?

![image](https://user-images.githubusercontent.com/2157566/88067568-70a6a800-cb6f-11ea-9460-2ed53d167c02.png)

**Comment by metavibor** [comment]
that should do just fine. Thank you!

**Comment by tischi** [comment]
Should be there with the latest update. Please let me know whether it works for you.

**Comment by metavibor** [comment]
I tested, it works good!
