### ISSUE TITLE
Measure min/max/average px value in any particular slice or ROI

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigDataProcessor2#91]
@metavibor
This is not possible currently. Adding ROIs is too much work currently, but may come in the future. However measuring the min/max/avg for one slice would be rather easy to add. Shall I do it?

**Comment by metavibor** [comment]
I think it would be useful for estimating parameters for the 8-bit conversion

**Comment by tischi** [comment]
If you now go [ Misc > Open in hyperstack viewer ] you can use the normal ImageJ functionality to measure anything you like.
Does that work for you?

**Comment by metavibor** [comment]
this works very well.
