### ISSUE TITLE
scijava 29.*

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#97]
@metavibor

Would you have a minute or two to test whether BDP2 is working? 
There have been many changes in Fiji...

It would be great if you could:

1. Download a new Fiji and update it
2. Add the BidDataProcessor update site
3. Check whether it works

**Comment by metavibor** [comment]
I'm on holidays at the moment. Will test it in two weeks time

**Comment by tischi** [comment]
@metavibor 
It should work now. I am closing the issue.
I hope you had nice holidays!
